name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "latest"

      - name: Install deps
        run: pnpm install

      - name: Build Rescript
        run: pnpm res:build
  
      - name: Build 
        run: pnpm build
  
