name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      BASE_URL: /satisfactory-planner/
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with: 
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ hashFiles('pnpm-*.yaml') }}

      - uses: pnpm/action-setup@v4
        with:
          version: "latest"

      - name: Install deps
        run: pnpm install

      - name: Build Rescript
        run: pnpm res:build
  
      - name: Build 
        run: pnpm build
  
      - name: Upload build
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
        name: deploy page
        id: deployment
